# Config Template
config-version: 1.0

# Define de messages lang
lang:
  # Define the default lang
  default: "pt_br"
  #Define if you want to use individual lang per player settings
  individual: true