# =====================[ CONFIGURATION FILE - SpawnerX ]===================== #
# Versão do arquivo de configuração. Não altere, a menos que orientado.
config-version: 1.0

# =====================[ IDIOMA DAS MENSAGENS ]===================== #
lang:
  # Idioma padrão utilizado nas mensagens do plugin.
  # Exemplo: "en_us", "pt_br"
  default: "pt_br"

  # Se verdadeiro, o plugin usará o idioma individual do jogador
  # (baseado nas configurações de idioma do Minecraft).
  individual: true

# =====================[ CONFIGURAÇÕES DO BANCO DE DADOS ]===================== #
database:

  # Define o tipo de banco de dados que será usado. (SQLite, MySQL ou MariaDB)
  type: "SQLite"

  # Define o prefix usado nos nomes das tabelas no banco.
  prefix: "spawnerx_"

  # Define o endereço do banco de dados. (SQLite não precisa disso.)
  host: "localhost"

  # Define o nome do banco de dados. (SQLite não precisa disso.)
  dbname: "minecraft"

  # Define o nome de usuário do banco de dados. (SQLite não precisa disso.)
  user: "yourUsername"

  # Define a senha do banco de dados. (SQLite não precisa disso.)
  pass: "yourPassword"

# =====================[ CONFIGURAÇÕES DE SPAWNERS ]===================== #
spawners:
  item:
    name: "&6Gerador de Monstros"
    lore:
      - ""
      - "&7Tipo: &f%display_name%"
  # Exibe um holograma acima do spawner (apenas se o empilhamento de spawners estiver ativo).
  hologram: false

  # Formato das linhas do holograma. Use variáveis como:
  # %stack_spawner% = quantidade de spawners
  # %type_mob% = tipo de mob
  hologram_format:
    - "&6&lMOBSPAWNER"
    - "&6%stack_spawner% &f%display_name%"

  # Configurações para empilhamento (stack) de spawners.
  stack:
    # Ativa o empilhamento de spawners do mesmo tipo próximos.
    enable: false

    # Número máximo de spawners que podem ser empilhados.
    max: 30

    # Distância máxima (em blocos) entre spawners para empilhamento (em segundos).
    distance: 5

  # Define se o spawner só pode ser dropado com Silk Touch.
  # true = apenas com picareta com Silk Touch
  # false = qualquer picareta
  only_silktouch: true

  # Configuração
  settings:
    # Intervalo para a geração de mobs em ticks.
    # 20 tickspeed = 1 segundo.
    delay: 40

    # Intervalo mínimo para a geração de um mob em ticks.
    # 20 tickspeed = 1 segundo.
    min_spawn_delay: 40

    # Intervalo máximo para a geração de um mob em ticks.
    # 20 tickspeed = 1 segundo.
    max_spawn_delay: 100

    # Número de mobs que o spawner tenta gerar a cada ciclo de spawn.
    spawn_count: 4

    # Define o raio (em blocos) em torno do spawner onde os mobs podem aparecer.
    spawn_range: 5

    # Distância máxima (em blocos) que um jogador precisa estar do spawner para que ele ative.
    required_player_range: 10

    # Número máximo de entidades vivas nas proximidades do spawner. Se houver mais que isso, o spawner pausa até que esse número caia.
    # Isto só funcionará caso o stack de mobs esteja desativado.
    max_nearby_entities: 16

# =====================[ CONFIGURAÇÕES DE MOBS ]===================== #
mobs:
  # Formato de exibição do nome da pilha de mobs.
  # Exemplo: x5 Cow
  format: "&6x%stack_mob% &f%display_name%"

  # Quantidade máxima de mobs que podem ser empilhados.
  stack_max: 300

  # Quantos mobs devem morrer por cada spawner ativo na chunk ao abater a pilha.
  kill_stack_per_spawner: 1

  # Desativa a IA dos mobs empilhados (eles ficam imóveis).
  ai_mob: true

  # Impede que o mob empilhado sofra knockback ao ser atingido.
  knockback_mob: true

  # Faz com que qualquer golpe elimine instantaneamente o mob empilhado.
  hitkill_mob: false

  # Se habilitado, faz com que utilizando shift mate o mob de 1 em 1.
  shift_kill_one: false

  # Se habilitado, deve matar todos os mobs estacados de uma vez.
  kill_all: false

  # Configurações de otimização de desempenho.
  performance_mob:
    # Remove a pilha de mobs se não houver nenhum jogador nas redondezas.
    stack_kill: true

    # Define o número mínimo de chunks de distância que o jogador deve estar para manter a pilha ativa.
    chunk: 5

  # Drops personalizados por tipo de mob.
  # Os mobs não listados aqui usarão o sistema padrão de drops do Minecraft.
  per_mob:
    cow:
      # Define o nome de exibição do mob.
      display_name: "Vaca"

      # Define a quantidade de exp que o mob irá dar pelo mínimo e máximo.
      # '-1' para default do minecraft
      experience:
        # Experiência mínima que o jogador irá ganhar.
        min: 1
        # Experiência máxima que o jogador irá ganhar.
        max: 3
      drops:
        drop1:
          # Selecione o tipo do drop que irá ter:
          # ITEM = dropará um item do minecraft.
          # COMMAND = irá gerar um comando via console.
          drop_type: "ITEM"

          # Insira o material pelo nome padrão do minecraft.
          material: "LEATHER"

          # Coloque a chance de dropar o item ou executar o comando.
          chance: 100

          # Sistema para controlar o ganho de itens raros por jogador e global.
          # Coloque '0' para desativar.
          drop_controller:
            # Defina o tempo em segundos para que o jogador entre em cooldown e só ganha o item após passar o tempo.
            player_delay: 120

            # Defina a quantidade máxima de itens que os jogadores podem conseguir no intervalo de tempo selecionado em 'global_delay'.
            global_amount: 2

            # Defina o tempo em segundos, caso a quantidade de itens selecionados em 'global_amount' for obtido para entrar em cooldown e ninguém ganhar mais.
            global_delay: 1400

          # Coloque a quantidade mínima de dropar o item ou executar o comando.
          min: 0

          # Coloque a quantidade máximo de dropar o item ou executar o comando.
          max: 2

          # Define a variação POSITIVA no drop.
          # Exemplo: Se positive_noise = 10, pode haver até +10% de variação no drop.
          # Valor padrão: 10%
          positive_noise: 10

          # Define a variação NEGATIVA no drop.
          # Exemplo: Se negative_noise = 10, pode haver até -10% de variação no drop.
          # Valor padrão: 10%
          negative_noise: 10

          # Define a porcentagem do multiplicador da looting que o jogador estiver utilizando por nível.
          # Exemplo: Looting 3 * 5% = 15% bônus de looting.
          # Valor Padrão: 5%
          looting: 5

        drop2:
          # Selecione o tipo do drop que irá ter:
          # ITEM = dropará um item do minecraft.
          # COMMAND = irá gerar um comando via console.
          drop_type: "ITEM"

          # Insira o material pelo nome padrão do minecraft.
          material: "STONE"

          # Coloque a chance em % de dropar o item ou executar o comando.
          chance: 10

          # Caso o jogador ganhar o item, ele terá um delay para ganhar novamente
          # 20 tickspeed = 1 segundo.
          # Coloque '0' para desativar.
          delay: 0

          # Coloque a quantidade mínima de dropar o item ou executar o comando.
          min: 0

          # Coloque a quantidade máximo de dropar o item ou executar o comando.
          max: 5

          # Define a variação POSITIVA no drop.
          # Exemplo: Se positive_noise = 10, pode haver até +10% de variação no drop.
          # Valor padrão: 10%
          positive_noise: 10

          # Define a variação NEGATIVA no drop.
          # Exemplo: Se negative_noise = 10, pode haver até -10% de variação no drop.
          # Valor padrão: 10%
          negative_noise: 10

          # Define a porcentagem do multiplicador da looting que o jogador estiver utilizando por nível.
          # Exemplo: Looting 3 * 5% = 15% bônus de looting.
          # Valor Padrão: 5%
          looting: 5

        drop3:
          drop_type: "COMMAND"

          # Coloque os comandos que deseja executar.
          commands:
            - "givespawner @player COW 1"
            - "givecash @player 100k"

          # Coloque a chance em % de dropar o item ou executar o comando.
          chance: 10

          # Caso o jogador ganhar o item, ele terá um delay para ganhar novamente
          # 20 tickspeed = 1 segundo.
          # Coloque '0' para desativar.
          delay: 0